source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem "jekyll-theme-console"
gem "jekyll-seo-tag"
gem "jekyll-sass-converter", "~> 2.2"
gem "webrick"
gem "csv"
gem "base64"
gem "bigdecimal"
gem "jekyll-feed"
